trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\'

name: $(date:yyyy).$(Month)$(rev:.r).0

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.0.100-preview4-011223'
  inputs:
    version: '3.0.100-preview4-011223'

- task: VersionAPPX@2
  displayName: 'Version MSIX'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/PhotoStore.csproj'

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageSigningEnabled=false /restore'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\AppxPackages'
    ArtifactName: 'drop'